from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Table
from reportlab.platypus import TableStyle
from reportlab.lib import colors
import pandas as pd
import numpy as np
from datetime import datetime
from tkinter import messagebox,filedialog



def drawMyRuler(pdf):
    pdf.drawString(100,810, 'x100')
    pdf.drawString(200,810, 'x200')
    pdf.drawString(300,810, 'x300')
    pdf.drawString(400,810, 'x400')
    pdf.drawString(500,810, 'x500')

    pdf.drawString(10,100, 'y100')
    pdf.drawString(10,200, 'y200')
    pdf.drawString(10,300, 'y300')
    pdf.drawString(10,400, 'y400')
    pdf.drawString(10,500, 'y500')
    pdf.drawString(10,600, 'y600')
    pdf.drawString(10,700, 'y700')
    pdf.drawString(10,800, 'y800')
    



"""
text = pdf.beginText(40, 680)
text.setFont("Courier", 18)
text.setFillColor(colors.red)
for line in textLines:
    text.textLine(line)

pdf.drawText(text)
"""

def maketable(data):

    table = Table(data)

    ts = TableStyle(
        [
        ('BOX',(0,0),(-1,-1),1,colors.black),
        ('LINEBEFORE',(2,1),(2,-1),1,colors.red),
        ('LINEABOVE',(0,2),(-1,2),1,colors.green),
        ('GRID',(0,0),(-1,-1),1,colors.black),
        ]
    )
    table.setStyle(ts)

    #elems = []
    #elems.append(table)
    #return elems
    


def draw_Report2(pdf,dataframe):
    
    #drawMyRuler(pdf)

    """for font in pdf.getAvailableFonts():
        print(font)"""

    #pdfmetrics.registerFont(TTFont('abc', 'SakBunderan.ttf'))
    #pdf.setFont('abc', 14)

    title = 'REMAL PUBLIC SCHOOL'
    subTitle = 'Pocket A-2, Sector-3, Rohini, Delhi'
    

    """pdf.line(30, 815, 570, 815)
    pdf.line(30, 30, 570, 30)
    pdf.line(30, 815, 30, 30)
    pdf.line(570, 815, 570, 30)"""


    #HEADER
    pdf.drawInlineImage("goodies/logo.png", 270, 755)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawCentredString(300, 740, "REMAL PUBLIC SR. SEC. SCHOOL")
    #pdf.setFillColorRGB(0, 0, 255)
    pdf.setFont("Helvetica", 11)
    pdf.drawCentredString(300,725, "Pocket A-2, Sector-3, Rohini, Delhi")
    pdf.drawCentredString(300,710, "Tele-011 47512024-29 : Email-remalps@gmail.com")


    pdf.line(30, 680, 570, 680)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawCentredString(300,665, "ATTENDANCE REPORT")
    #pdf.drawCentredString(300,665, "ATTENDANCE REPORT (ABSENTEES)")
    pdf.line(30, 660, 570, 660)



    #DETAILS TAB
    pdf.setFont("Helvetica", 10)
    dd="Date : "+datee
    pdf.drawString(40,685,dd)
    page_st="Page "+str(p_count)+" of "+str(t_pages)
    pdf.drawString(500,685,page_st)

    #print(dataframe)
    table = Table(dataframe,rowHeights=19)

    ts = TableStyle(
        [
        ('BOX',(0,0),(-1,-1),1,colors.grey),
        #('LINEBEFORE',(0,1),(2,-5),1,colors.red),
        #('LINEABOVE',(0,1),(-1,2),1,colors.green),
        ('GRID',(0,0),(-1,-1),1,colors.white)
        
        ]
    )

    data_len = len(dataframe)

    for each in range(data_len):
        if each==0:
            table.setStyle(TableStyle([('BACKGROUND', (0, each), (-1, each), colors.black)]))
            table.setStyle(TableStyle([('TEXTCOLOR', (0, each), (-1, each), colors.white)]))
        elif each%2==1:
            table.setStyle(TableStyle([('BACKGROUND', (0, each), (-1, each), colors.lightgrey)]))    

    table.setStyle(ts)

    
    length=len(dataframe)

    original=620
    i=0
    while (i<length):
        original-=20
        i+=1
    if i>10:
        original+=20
    if i>20:
        original+=40

    table.wrapOn(pdf, 0, 0)
    table.drawOn(pdf, 50, original)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(490, 40, "CHECKER")
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawCentredString(300, 20, "Generated by CAAS | By Harsh Vardhan")
    pdf.showPage()
    #pdf.save()


def split2(pdf,data):
    global p_count
    p_count+=1
    if len(data)>31:
        if data[0][0]!="ID NO":
            d=[]
            d.append(['ID NO', 'NAME', 'TYPE','CLASS', 'DATE', 'STATUS ', 'DATE    TIMESTAMP    (IST)'])
            for l in data:
                d.append(l)
            #data=['NO.','ID NO', 'NAME', 'TYPE','CLASS', 'DATE', 'STATUS', 'TIMESTAMP (IST)']+data
            data=d
        draw_Report2(pdf,data[:31])
        new_data=pd.DataFrame(data).iloc[31:]
        new=[new_data.columns.tolist()]+[new_data.values.tolist()]
        split2(pdf,new_data.values.tolist())    
    else:
        if data[0][0]!="ID NO":
            d=[]
            d.append(['ID NO', 'NAME', 'TYPE','CLASS', 'DATE', 'STATUS ', 'DATE    TIMESTAMP    (IST)'])
            for l in data:
                d.append(l)
            data=d
        draw_Report2(pdf,data)
        pdf.save()
        messagebox.showinfo("Export","PDF exported successfully")

t_pages,p_count=0,0
datee=""

def receive_Data2(data):
    print("RECEIVED", data)
    #data=data.insert(loc=0, column='NO.', value=np.arange(len(data)))
    #data["NO."]=(range(1, 1 + len(data)))
    global t_pages,datee
    export_file_path = filedialog.asksaveasfilename(defaultextension='.pdf')
    fileName = 'report.pdf'
    documentTitle = 'CASS | Report'
    pdf = canvas.Canvas(export_file_path)
    pdf.setTitle(documentTitle)
    t_pages=len(data)//30
    print("Total Pages : ",t_pages)
    datee = str(datetime.now().strftime("%d/%m/%Y, %H:%M:%S"))
    split2(pdf,data)


data2 = [
    ['NO.','ID NO', 'NAME', 'TYPE','CLASS', 'DATE', 'STATUS', 'TIMESTAMP (IST)'],
    ['1','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A'],
    ['2','5999', 'Harsh Vardhan Yadav', 'Student','XII-C', '01/03/2021', 'ABSENT', 'N/A']
]
#receive_Data2(data)
